### ISSUE TITLE
Input element value is reset on change

### ISSUE THREAD

**Issue by jodelamo** [Riim/Rionite#2]
After `change` triggers on an `input` field, through e.g. pressing enter or a `blur` event, its value is cleared (the page is not reloaded). Is this the expected behavior?

A fairly minimal example:

``` javascript
import { d, component } from 'rista';

component('editable', {
  @d.observable count: 0,

  renderInner() {
    return `
      <input type="text" rt-change="onChange">
      <div>Characters: ${ this.count }</div>
    `;
  },

  onChange(event) {
    this.count = event.target.value.length;
  }
});
```

**Comment by Riim** [comment]
Hi! As far as I know, with React this is solved in a similar way: http://jsfiddle.net/yuvvqzx9/. For convenience, you can make custom input-component: http://jsfiddle.net/9kg2Ly2v/.

**Comment by jodelamo** [comment]
That seems to work. Thanks!
